from typing import Protocol


class ExecutionBackend(Protocol):
    name: str
    version: str
    harness_kind: str
    harness_filename: str
    harness_instructions: str
    def environment(self, workspace) -> dict[str, str]: ...
    def read_only_roots(self) -> list: ...
    def parse_test_result(self, check, text): ...
    def probe_command(self) -> list[str]: ...
    def experiment_command(self) -> list[str]: ...
    def version_command(self) -> list[str]: ...
    def capabilities(self, check): ...


class AgentBackend(Protocol):
    name: str
    mock: bool
    def probe(self, runner): ...
    def analyze(self, runner, prompt, directory, snapshot_id, timeout, response_type): ...


class VerifierBackend(Protocol):
    name: str
    def probe(self, runner): ...
    def check(self, runner, model, timeout): ...
    def calibrate(self, runner, model, bundle, experiment, timeout): ...
    def reachability(self, runner, model, bundle, requirement, timeout): ...
