from typing import Protocol


class ExecutionBackend(Protocol):
    name: str
    version: str
    harness_kind: str
    harness_filename: str
    harness_instructions: str
    def environment(self, workspace) -> dict[str, str]: ...
    def read_only_roots(self) -> list: ...
    def parse_test_result(self, check, text): ...
    def experiment_command(self) -> list[str]: ...
    def version_command(self) -> list[str]: ...


class AgentBackend(Protocol):
    name: str
    mock: bool
    def probe(self, runner): ...
    def investigate(self, runner, prompt, directory, snapshot_id, timeout, session_id=None): ...
