import json
from pathlib import Path
sources=[
 dict(id='pipeline-interface',file='transport.go',start_line=109,end_line=140,kind='interface_statement'),
 dict(id='pipeline-result',file='replication.go',start_line=534,end_line=566,kind='code_observation'),
 dict(id='replication-update',file='replication.go',start_line=646,end_line=665,kind='code_observation'),
 dict(id='inmem-pipeline-factory',file='inmem_transport.go',start_line=87,end_line=100,kind='code_observation'),
 dict(id='inmem-pipeline-producer',file='inmem_transport.go',start_line=259,end_line=309,kind='code_observation'),
 dict(id='inmem-pipeline-submit',file='inmem_transport.go',start_line=311,end_line=374,kind='code_observation'),
 dict(id='net-pipeline-producer',file='net_transport.go',start_line=839,end_line=860,kind='code_observation'),
 dict(id='net-response-decoder',file='net_transport.go',start_line=769,end_line=790,kind='code_observation'),
 dict(id='future-status-contract',file='future.go',start_line=13,end_line=23,kind='interface_statement'),
 dict(id='future-completion',file='future.go',start_line=90,end_line=135,kind='code_observation'),
 dict(id='append-future-access',file='future.go',start_line=295,end_line=314,kind='code_observation'),
 dict(id='ordinary-result-control',file='replication.go',start_line=229,end_line=263,kind='code_observation'),
]
claim_id='failed-pipeline-response-not-consumed'
binding_ids=['pipeline-consumer-binding','inmem-producer-binding']
limitations=[
 'This check ends at AppendFuture.Response interface access. It does not establish invalid log matching, a false quorum, loss of leader authority, or an unsafe application.',
 'The local consumer is invoked directly with minimal Raft/followerReplication state; election, log persistence and the full replication sender loop are not executed.',
 'The successful control peer is scripted at the RPC interface. Its acknowledgement is not evidence of durable follower storage.',
 'Ready futures are collected from the real InmemTransport pipeline and delivered through a delegating channel adapter in original order. Delayed scheduling after completion is permitted, but a full deployment schedule is not reproduced.',
 'NetworkTransport publishes error-bearing futures too by source reading; this check does not execute that transport or byte decoding.',
 'The existing zero-valued timeout response has Success=false and may prevent match advancement despite invalid interface access. The check must not promote the access result to a commit-safety finding.'
]
grounding={
 'source_ids':['pipeline-result','inmem-pipeline-producer','inmem-pipeline-submit','append-future-access','ordinary-result-control'],
 'expectation_ids':['pipeline-interface','future-status-contract'],
 'binding_ids':binding_ids,
 'derivation':'AppendFuture.Response explicitly has a successful-Error-return precondition (transport.go:137-140); Future.Error supplies actual completion status. A completed future whose Error returns non-nil therefore has no valid Response to consume. The obligation is the necessary safety condition that a failed future is not accessed via Response, not a requirement to consume every successful future. Receipt from Consumer can establish completion but cannot erase a non-nil result: the built-in inmem producer publishes a timeout future after respond(error), and the network producer likewise publishes after decode errors. This expectation is an interface-use responsibility, distinct from durable-prefix or consensus correctness.',
 'applicability':'pipelineDecode receives AppendFuture through AppendPipeline.Consumer and calls its Response method. The selected concrete producer is built-in InmemTransport under a withheld response exceeding its configured timeout; the failure is generated by actual producer code, not assigned by the harness.',
 'unresolved':limitations,
 'conflicts':[],
 'alternatives':['The ready channel synchronizes completion and may eliminate waiting, but does not make an errored response valid.','A zero-valued timeout response and !resp.Success can prevent log progress even if the Response access precondition is violated.']
}
q={
 'disposition':'ready_for_check','preferred_check':'direct_test',
 'question':'When built-in InmemTransport publishes a completed AppendFuture with a non-nil timeout error, does Raft.pipelineDecode call Response on that same failed future? The discriminator is a delegated Response access count correlated with the actual Future.Error status after consumer completion.',
 'importance':'pipelineDecode uses response fields to accept replication support or reject the pipeline. Reading a response outside its interface validity condition can make support interpretation depend on unspecified error-state fields. The selected endpoint is only failed-future Response access; unsafe support and system consequences remain unestablished.',
 'source_ids':[s['id'] for s in sources],
 'participants':['Raft pipelineDecode consumer','Built-in InmemTransport pipeline producer','A connected in-memory peer with a withheld response','A scripted successful/rejecting peer control'],
 'objects':['One identified AppendFuture per timeout/success operation','Its independent request identity and response allocation','A delegating future wrapper','Per-scenario followerReplication and commitment'],
 'contexts':['A1 support consumption at AppendFuture interface','One term 4 and fixed two-voter configuration in an isolated consumer fixture','Response delay beyond transport deadline; no Byzantine data or storage failure injection','No leadership replacement: the preceding cross-incarnation question remains explained'],
 'event_paths':[
  'AppendEntries admits a request into the connected peer transport and registers its actual future with inprogressCh.',
  'The timeout scenario withholds the RPC reply; inmemPipeline.decodeResponses calls respond(error) and publishes the future on doneCh. The success control replies through RPC.Respond and the same producer publishes its future.',
  'The harness retains future identity from submission to Consumer publication without calling Error or Response on the measured future.',
  'A wrapper counts Response calls while delegating all method behavior. pipelineDecode consumes the real completed future through an adapted ready channel.',
  'An independently completed rejection future is queued after the measured future to stop a successful decoding path. Consumer completion is required; timeout is a test infrastructure failure, not a property verdict.',
  'After finishCh closes, the harness reads the actual measured future Error, verifies the intended producer outcome, and emits the Response count for that operation.'
 ],
 'activity_classes':['A1'], 'behavior_ids':[], 'fact_ids':[],
 'obligation_relation_kind':'consumption',
 'counterevidence':grounding['alternatives']+['Ordinary replicateTo checks the transport call error before reading response fields.','Old/new commitment object isolation from the accepted prior question remains intact and does not establish this interface precondition.'],
 'unknowns':limitations,
 'priority':2,
 'trigger_rationale':'The earlier source review left pipeline future validity explicitly unknown. Cross-path reading now shows ordinary replication checks an error while pipelineDecode reads Response directly. Both built-in producers publish failures. The explicit AppendFuture contract grounds a local check; asymmetry alone is not treated as a safety defect.'
}
claim={
 'id':claim_id,'kind':'obligation',
 'description':'For a completed AppendFuture consumed by Raft.pipelineDecode whose Error result is non-nil, that consumer must not call Response on that future.',
 'source_ids':['pipeline-interface','future-status-contract','pipeline-result','inmem-pipeline-producer'],
 'scope':{'description':'Local failed-future response-validity consumption at the AppendFuture interface, using built-in in-memory timeout production and an isolated pipelineDecode consumer.',
          'assumptions':['A permitted delayed RPC reply may exceed the configured InmemTransport timeout.','The ready-future channel adapter preserves the submitted future identity, completion state and order.'],
          'excluded':limitations,
          'parameters':{'term':4,'request_index':2,'transport_timeout_ms':100,'scenarios':['timeout','success']}},
 'pending':[], 'grounding':grounding
}
bindings=[]
for bid,mid,symbol,start,end,desc in [
 ('pipeline-consumer-binding','pipeline-result','pipelineDecode',534,566,'Consumer reads Response, then checks term and success; its return closes finishCh.'),
 ('inmem-producer-binding','inmem-pipeline-producer','decodeResponses',272,309,'Built-in inmemPipeline completes and publishes normal and timeout futures.')]:
 bindings.append({'id':bid,'material_id':mid,'symbol':symbol,'start_line':start,'end_line':end,'description':desc,'pending':[],
 'associations':[{'claim_id':claim_id,'source_ids':['pipeline-interface',mid],'rationale':desc}],
 'anchor':{'kind':'declaration','material_id':mid,'start_line':start,'end_line':end,'symbol':symbol,'source_ids':[mid],'boundary_complete':True}})
candidate={'action':'obligation','rationale':'Select the previously unresolved pipeline validity relation as a distinct local question. The prior cross-leader ownership explanation is retained. The interface supplies the expectation and actual inmem timeout production supplies a controllable input; no broader protocol violation is assumed.','sources':[], 'question':q,'obligation':claim,'bindings':bindings}
plan={
 'description':'Measure failed-future Response access in actual pipelineDecode with real built-in timeout futures and a successful producer control.',
 'claim_id':claim_id,'binding_ids':binding_ids,
 'harness':{'kind':'go_test','source':'','files':{},
  'description':'TestAssurancePipelineFailedFutureResponse admits one request per scenario, obtains its real completed future without inspecting response/status, invokes the actual pipeline consumer with a delegating Response counter, and observes completion and status. A subsequent completed rejection stops the success path independently of the property.',
  'semantic_changes':['No target source or dependency changes.','Direct invocation of pipelineDecode substitutes the leader lifecycle and sending loop.','Scripted peer replies for success and stopping rejection substitute follower handling. Timeout error production uses the actual built-in producer.','A channel adapter schedules already-completed futures and a method wrapper counts Response access without changing return values.'],
  'prerequisites':[
    {'alias':'admitted','event':'request_admitted','conditions':[{'field':'admitted','op':'eq','value':True}]},
    {'alias':'ready','event':'future_ready','conditions':[{'field':'published','op':'eq','value':True},{'field':'operation_id','op':'eq','reference':'admitted.operation_id'}]}
  ],'legality':grounding},
 'monitors':[{'id':'failed-future-access-monitor','checker_id':'failed-future-no-response','event':'consumer_completed','binding_ids':binding_ids,'grounding':grounding,'applicability_conditions':[]}],
 'observable_properties':[{'checker_id':'failed-future-no-response','kind':'event_implication',
   'trigger':{'field':'completed','op':'eq','value':True},
   'antecedent':{'field':'future_failed','op':'eq','value':True},
   'assertion':{'field':'response_calls','op':'eq','value':0},
   'identity_fields':['operation_id'],
   'description':'For each completed operation, a non-nil actual future error implies zero Response calls by the consumer. A successful control is permitted and does not require Response access or progress.'}],
 'uncertainties':limitations
}
submission={'action':'check','rationale':'Submit a complete direct check for the interface-grounded failed-future consumption obligation. Actual InmemTransport timeout production and delegated method-access counting provide the discriminator. No local process result is formal evidence.','sources':sources,'candidate':candidate,'plan_path':'pipeline_plan.json','harness_path':'pipeline_error_test.go','files':{}}
Path('pipeline_plan.json').write_text(json.dumps(plan,indent=2)+'\n')
Path('submission.json').write_text(json.dumps(submission,indent=2)+'\n')
import jsonschema
jsonschema.validate(submission,json.load(open('../native-submission.schema.json')))
# The runner supplies the separately submitted source before product validation.
plan['harness']['source']=Path('pipeline_error_test.go').read_text()
jsonschema.validate(plan,json.load(open('../product-schemas.json'))['DirectCheckPlan'])
print('Submission and assembled direct-check metadata pass JSON schema validation.')
